# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20181010_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='server_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
