# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_log_server_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='server_name',
            field=models.CharField(default='my_server', max_length=50),
            preserve_default=False,
        ),
    ]
